// Generates src/view/icons.ts from lucide-static SVGs so toolbar icons are
// bundled into the plugin and never depend on Obsidian's icon registry
// (which proved unreliable on Obsidian Mobile / Android).
//
// Run after changing the ICON list:  node scripts/gen-icons.mjs

import { readFileSync, writeFileSync } from "fs";

const ICONS = [
  "pen",
  "pencil",
  "highlighter",
  "eraser",
  "mouse-pointer",
  "shapes",
  "ruler",
  "smile",
  "trash-2",
  "undo-2",
  "redo-2",
  "chevron-left",
  "chevron-right",
  "plus",
  "layout-template",
  "layout-grid",
  "file-plus",
  "image-plus",
  "more-vertical",
  "pen-tool",
  "pen-line",
  "palette",
  "brush",
  "type",
  "sparkles",
  "lasso",
  "circle-plus",
];

const entries = ICONS.map((name) => {
  let svg = readFileSync(`node_modules/lucide-static/icons/${name}.svg`, "utf8");
  svg = svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\s+width="24"/, ' width="20"')
    .replace(/\s+height="24"/, ' height="20"')
    .replace(/class="[^"]*"/, 'class="ink-icon"')
    .replace(/\s*\n\s*/g, " ")
    .trim();
  if (!svg.includes('class="ink-icon"')) {
    svg = svg.replace("<svg ", '<svg class="ink-icon" ');
  }
  return `  "${name}": \`${svg}\`,`;
});

const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Inline lucide icons (https://lucide.dev, ISC license), bundled so the
// toolbar renders identically on every Obsidian platform and version.

const ICONS: Record<string, string> = {
${entries.join("\n")}
};

export type IconName = keyof typeof ICONS & string;

/** Replace an element's content with a bundled SVG icon. */
export function setToolIcon(el: HTMLElement, name: string): void {
  const svg = ICONS[name];
  if (svg) {
    el.innerHTML = svg;
  } else {
    console.error("Ink Studio: missing bundled icon", name);
    el.setText(name);
  }
}
`;

writeFileSync("src/view/icons.ts", out);
console.log(`Wrote src/view/icons.ts with ${ICONS.length} icons`);
